"""Initial migration with User table

Revision ID: ea16599a186c
Revises: 
Create Date: 2025-07-12 08:46:30.382590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea16599a186c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'CUSTOMER_SERVICE', 'DEVELOPER', 'FINANCE', name='userrole'), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('specialized_field', sa.String(length=255), nullable=True),
    sa.Column('default_commission_rate', sa.Float(), nullable=True),
    sa.Column('financial_account', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
